Fix build on macOS due to unwanted characters.
Building fails with:
Eeprom.cpp:1:1: error: stray '\357' in program
 ﻿/*
 ^
Eeprom.cpp:1:2: error: stray '\273' in program
 ﻿/*
  ^
Eeprom.cpp:1:3: error: stray '\277' in program
 ﻿/*
   ^